# official python runtime as parent
FROM python:3.11-slim

# Set Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

#install system dependencies (optional, but sometimes needed for packages like redis/request/httpx)
RUN apt-get update && apt-get install -y build-essential



#for installing Python Dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy the project under app directory
COPY . .

#Expose the port :8000 for fastapi
EXPOSE 8000

# command to run app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]